[package]
name = "inmemex"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3.9", features = ["processthreadsapi", "memoryapi", "synchapi", "winbase", "winnt"] }
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
